[toolchain]
anchor_version = "0.28.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
tic_tac_toe = "6nGpXemBCiPJRFdzheSMQAPnu7ntyfQiycNjMBpbLXaa"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/freeCodeCampWeb3/solana-curriculum/tutorials/player-one.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
